version: "2" # docker-compose version
services: #服务列表
  # 其他配置参考 https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi/
  nonebot:
    build: .
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./:/app/"
#    ports:
#      - "8082:8082" # 映射端口到宿主机 宿主机端口:容器端口
    env_file:
      - ".env.prod" # fastapi 使用的环境变量文件
    environment:
      - ENVIRONMENT=prod # 配置 nonebot 运行环境，此项会被 .env 文件覆盖
      - APP_MODULE=bot:app # 配置 asgi 入口
      - SECRET # 通过 SECRET=xxx nb up -d 传递密钥
      - ACCESS_TOKEN # 通过 ACCESS_TOKEN=xxx nb up -d 传递密钥
      - MAX_WORKERS=1 # 如果你有多个QQ，且存在 self_id 指定，多个 worker 会导致无法找到其他 websocket 连接
    hostname: nonebot
    depends_on: #依赖于
      - mysql
    network_mode: host # 使用 host 网络模式，不需要指定网络名称
    shm_size: "1g" # 分配共享内存
#    networks:
#      - my-net

  cqhttp:
    image: ubuntu:18.04
    build: ./go-cqhttp_windows_amd64
#    links:
#      - nonebot:nonebot
#    ports:
#      - "8083:8083"
    network_mode: host # 使用 host 网络模式，不需要指定网络名称
  #    networks:
#      - my-net


  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "qq_bot_hdu"
#      MYSQL_USER: "root" # MYSQL_USER和MYSQL_PASSWORD是用于配置普通用户的，不能用于root用户
#    ports:
#      - "3306:3306"
    network_mode: host # 使用 host 网络模式，不需要指定网络名称
#    networks:
#      - my-net
#networks:
#  my-net:
#    external: true